using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "bad36918855acb52")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.3")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Properties</summary>
	[PublishedContentModel("properties")]
	public partial class Properties : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "properties";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Properties(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Properties, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Singapore</summary>
	[PublishedContentModel("singapore")]
	public partial class Singapore : Properties
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "singapore";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Singapore(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Singapore, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Bedroom Type
		///</summary>
		[ImplementPropertyType("bedroomType")]
		public IEnumerable<string> BedroomType
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("bedroomType"); }
		}

		///<summary>
		/// Category
		///</summary>
		[ImplementPropertyType("category")]
		public string Category
		{
			get { return this.GetPropertyValue<string>("category"); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("cn_name")]
		public string Cn_name
		{
			get { return this.GetPropertyValue<string>("cn_name"); }
		}

		///<summary>
		/// Properties
		///</summary>
		[ImplementPropertyType("cn_properties")]
		public IHtmlString Cn_properties
		{
			get { return this.GetPropertyValue<IHtmlString>("cn_properties"); }
		}

		///<summary>
		/// Sale Start Price
		///</summary>
		[ImplementPropertyType("cn_saleStartPrice")]
		public string Cn_saleStartPrice
		{
			get { return this.GetPropertyValue<string>("cn_saleStartPrice"); }
		}

		///<summary>
		/// Concierge Services?
		///</summary>
		[ImplementPropertyType("conciergeServices")]
		public bool ConciergeServices
		{
			get { return this.GetPropertyValue<bool>("conciergeServices"); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("en_name")]
		public string En_name
		{
			get { return this.GetPropertyValue<string>("en_name"); }
		}

		///<summary>
		/// Properties
		///</summary>
		[ImplementPropertyType("en_properties")]
		public IHtmlString En_properties
		{
			get { return this.GetPropertyValue<IHtmlString>("en_properties"); }
		}

		///<summary>
		/// Sale Start Price
		///</summary>
		[ImplementPropertyType("en_saleStartPrice")]
		public string En_saleStartPrice
		{
			get { return this.GetPropertyValue<string>("en_saleStartPrice"); }
		}

		///<summary>
		/// Five Bedroom Floor Size
		///</summary>
		[ImplementPropertyType("fiveBedroomFloorSize")]
		public IEnumerable<string> FiveBedroomFloorSize
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("fiveBedroomFloorSize"); }
		}

		///<summary>
		/// One Bedroom Floor Size
		///</summary>
		[ImplementPropertyType("floorSize")]
		public IEnumerable<string> FloorSize
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("floorSize"); }
		}

		///<summary>
		/// Four Bedroom Floor Size
		///</summary>
		[ImplementPropertyType("fourBedroomFloorSize")]
		public IEnumerable<string> FourBedroomFloorSize
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("fourBedroomFloorSize"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("image"); }
		}

		///<summary>
		/// Immediate Occupation
		///</summary>
		[ImplementPropertyType("immediateOccupation")]
		public IEnumerable<string> ImmediateOccupation
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("immediateOccupation"); }
		}

		///<summary>
		/// Name
		///</summary>
		[ImplementPropertyType("in_name")]
		public string In_name
		{
			get { return this.GetPropertyValue<string>("in_name"); }
		}

		///<summary>
		/// Properties
		///</summary>
		[ImplementPropertyType("in_properties")]
		public IHtmlString In_properties
		{
			get { return this.GetPropertyValue<IHtmlString>("in_properties"); }
		}

		///<summary>
		/// Sale Start Price
		///</summary>
		[ImplementPropertyType("in_saleStartPrice")]
		public string In_saleStartPrice
		{
			get { return this.GetPropertyValue<string>("in_saleStartPrice"); }
		}

		///<summary>
		/// Is External Property?
		///</summary>
		[ImplementPropertyType("isExternalProperty")]
		public bool IsExternalProperty
		{
			get { return this.GetPropertyValue<bool>("isExternalProperty"); }
		}

		///<summary>
		/// Latitude
		///</summary>
		[ImplementPropertyType("latitude")]
		public string Latitude
		{
			get { return this.GetPropertyValue<string>("latitude"); }
		}

		///<summary>
		/// Longitude
		///</summary>
		[ImplementPropertyType("longitude")]
		public string Longitude
		{
			get { return this.GetPropertyValue<string>("longitude"); }
		}

		///<summary>
		/// Penthouse Floor Size
		///</summary>
		[ImplementPropertyType("penthouseFloorSize")]
		public IEnumerable<string> PenthouseFloorSize
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("penthouseFloorSize"); }
		}

		///<summary>
		/// Sale / Lease: Please select
		///</summary>
		[ImplementPropertyType("saleLease")]
		public IEnumerable<string> SaleLease
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("saleLease"); }
		}

		///<summary>
		/// SkySuite Floor Size
		///</summary>
		[ImplementPropertyType("skySuiteFloorSize")]
		public IEnumerable<string> SkySuiteFloorSize
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("skySuiteFloorSize"); }
		}

		///<summary>
		/// SkyVilla Floor Size
		///</summary>
		[ImplementPropertyType("skyVillaFloorSize")]
		public IEnumerable<string> SkyVillaFloorSize
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("skyVillaFloorSize"); }
		}

		///<summary>
		/// Tenure: Please choose
		///</summary>
		[ImplementPropertyType("tenure")]
		public string Tenure
		{
			get { return this.GetPropertyValue<string>("tenure"); }
		}

		///<summary>
		/// Three Bedroom Floor Size
		///</summary>
		[ImplementPropertyType("threeBedroomFloorSize")]
		public IEnumerable<string> ThreeBedroomFloorSize
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("threeBedroomFloorSize"); }
		}

		///<summary>
		/// Two Bedroom Floor Size
		///</summary>
		[ImplementPropertyType("twoBedroomFloorSize")]
		public IEnumerable<string> TwoBedroomFloorSize
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("twoBedroomFloorSize"); }
		}

		///<summary>
		/// Unit Type
		///</summary>
		[ImplementPropertyType("unitType")]
		public IEnumerable<string> UnitType
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("unitType"); }
		}
	}

	/// <summary>International</summary>
	[PublishedContentModel("international")]
	public partial class International : Properties
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "international";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public International(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<International, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("cn_city")]
		public string Cn_city
		{
			get { return this.GetPropertyValue<string>("cn_city"); }
		}

		///<summary>
		/// Contact Information
		///</summary>
		[ImplementPropertyType("cn_contactInformation")]
		public string Cn_contactInformation
		{
			get { return this.GetPropertyValue<string>("cn_contactInformation"); }
		}

		///<summary>
		/// Properties Detail
		///</summary>
		[ImplementPropertyType("cn_propertiesDetail")]
		public IHtmlString Cn_propertiesDetail
		{
			get { return this.GetPropertyValue<IHtmlString>("cn_propertiesDetail"); }
		}

		///<summary>
		/// Residence Name
		///</summary>
		[ImplementPropertyType("cn_residenceName")]
		public string Cn_residenceName
		{
			get { return this.GetPropertyValue<string>("cn_residenceName"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("en_city")]
		public string En_city
		{
			get { return this.GetPropertyValue<string>("en_city"); }
		}

		///<summary>
		/// Contact Information
		///</summary>
		[ImplementPropertyType("en_contactInformation")]
		public string En_contactInformation
		{
			get { return this.GetPropertyValue<string>("en_contactInformation"); }
		}

		///<summary>
		/// Properties Detail
		///</summary>
		[ImplementPropertyType("en_propertiesDetail")]
		public IHtmlString En_propertiesDetail
		{
			get { return this.GetPropertyValue<IHtmlString>("en_propertiesDetail"); }
		}

		///<summary>
		/// Residence Name
		///</summary>
		[ImplementPropertyType("en_residenceName")]
		public string En_residenceName
		{
			get { return this.GetPropertyValue<string>("en_residenceName"); }
		}

		///<summary>
		/// External Website Link
		///</summary>
		[ImplementPropertyType("externalLink")]
		public string ExternalLink
		{
			get { return this.GetPropertyValue<string>("externalLink"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return this.GetPropertyValue<IPublishedContent>("image"); }
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("in_city")]
		public string In_city
		{
			get { return this.GetPropertyValue<string>("in_city"); }
		}

		///<summary>
		/// Contact Information
		///</summary>
		[ImplementPropertyType("in_contactInformation")]
		public string In_contactInformation
		{
			get { return this.GetPropertyValue<string>("in_contactInformation"); }
		}

		///<summary>
		/// Properties Detail
		///</summary>
		[ImplementPropertyType("in_propertiesDetail")]
		public IHtmlString In_propertiesDetail
		{
			get { return this.GetPropertyValue<IHtmlString>("in_propertiesDetail"); }
		}

		///<summary>
		/// Residence Name
		///</summary>
		[ImplementPropertyType("in_residenceName")]
		public string In_residenceName
		{
			get { return this.GetPropertyValue<string>("in_residenceName"); }
		}
	}

	/// <summary>International Sites</summary>
	[PublishedContentModel("internationalSites")]
	public partial class InternationalSites : Properties
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "internationalSites";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public InternationalSites(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<InternationalSites, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Singapore Sites</summary>
	[PublishedContentModel("singaporeSites")]
	public partial class SingaporeSites : Properties
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "singaporeSites";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SingaporeSites(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SingaporeSites, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Detail</summary>
	[PublishedContentModel("detail")]
	public partial class Detail : Properties
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "detail";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Detail(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Detail, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Html Content
		///</summary>
		[ImplementPropertyType("cn_htmlContent")]
		public string Cn_htmlContent
		{
			get { return this.GetPropertyValue<string>("cn_htmlContent"); }
		}

		///<summary>
		/// Html Content
		///</summary>
		[ImplementPropertyType("en_htmlContent")]
		public string En_htmlContent
		{
			get { return this.GetPropertyValue<string>("en_htmlContent"); }
		}

		///<summary>
		/// Html Content
		///</summary>
		[ImplementPropertyType("in_htmlContent")]
		public string In_htmlContent
		{
			get { return this.GetPropertyValue<string>("in_htmlContent"); }
		}
	}

	/// <summary>CDLHomes</summary>
	[PublishedContentModel("cDLHomes")]
	public partial class CDlhomes : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "cDLHomes";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CDlhomes(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CDlhomes, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel, IBanner
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banners
		///</summary>
		[ImplementPropertyType("banners")]
		public Newtonsoft.Json.Linq.JToken Banners
		{
			get { return Umbraco.Web.PublishedContentModels.Banner.GetBanners(this); }
		}
	}

	// Mixin content Type 1155 with alias "banner"
	/// <summary>Banner</summary>
	public partial interface IBanner : IPublishedContent
	{
		/// <summary>Banners</summary>
		Newtonsoft.Json.Linq.JToken Banners { get; }
	}

	/// <summary>Banner</summary>
	[PublishedContentModel("banner")]
	public partial class Banner : PublishedContentModel, IBanner
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "banner";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Banner(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Banner, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banners
		///</summary>
		[ImplementPropertyType("banners")]
		public Newtonsoft.Json.Linq.JToken Banners
		{
			get { return GetBanners(this); }
		}

		/// <summary>Static getter for Banners</summary>
		public static Newtonsoft.Json.Linq.JToken GetBanners(IBanner that) { return that.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("banners"); }
	}

	// Mixin content Type 1158 with alias "menu"
	/// <summary>Menu</summary>
	public partial interface IMenu : IPublishedContent
	{
		/// <summary>Menu Ttitle (Chinese)</summary>
		string Cn_menuTtitle { get; }

		/// <summary>Hide Menu</summary>
		bool HideMenu { get; }

		/// <summary>Menu Title (Indonesia)</summary>
		string In_menuTitle { get; }

		/// <summary>Menu Title</summary>
		string MenuTitle { get; }
	}

	/// <summary>Menu</summary>
	[PublishedContentModel("menu")]
	public partial class Menu : PublishedContentModel, IMenu
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "menu";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Menu(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Menu, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Menu Ttitle (Chinese)
		///</summary>
		[ImplementPropertyType("cn_menuTtitle")]
		public string Cn_menuTtitle
		{
			get { return GetCn_menuTtitle(this); }
		}

		/// <summary>Static getter for Menu Ttitle (Chinese)</summary>
		public static string GetCn_menuTtitle(IMenu that) { return that.GetPropertyValue<string>("cn_menuTtitle"); }

		///<summary>
		/// Hide Menu
		///</summary>
		[ImplementPropertyType("hideMenu")]
		public bool HideMenu
		{
			get { return GetHideMenu(this); }
		}

		/// <summary>Static getter for Hide Menu</summary>
		public static bool GetHideMenu(IMenu that) { return that.GetPropertyValue<bool>("hideMenu"); }

		///<summary>
		/// Menu Title (Indonesia)
		///</summary>
		[ImplementPropertyType("in_menuTitle")]
		public string In_menuTitle
		{
			get { return GetIn_menuTitle(this); }
		}

		/// <summary>Static getter for Menu Title (Indonesia)</summary>
		public static string GetIn_menuTitle(IMenu that) { return that.GetPropertyValue<string>("in_menuTitle"); }

		///<summary>
		/// Menu Title
		///</summary>
		[ImplementPropertyType("menuTitle")]
		public string MenuTitle
		{
			get { return GetMenuTitle(this); }
		}

		/// <summary>Static getter for Menu Title</summary>
		public static string GetMenuTitle(IMenu that) { return that.GetPropertyValue<string>("menuTitle"); }
	}

	/// <summary>Contact Us</summary>
	[PublishedContentModel("contactUs")]
	public partial class ContactUs : PublishedContentModel, IMenu
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Menu Ttitle (Chinese)
		///</summary>
		[ImplementPropertyType("cn_menuTtitle")]
		public string Cn_menuTtitle
		{
			get { return Umbraco.Web.PublishedContentModels.Menu.GetCn_menuTtitle(this); }
		}

		///<summary>
		/// Hide Menu
		///</summary>
		[ImplementPropertyType("hideMenu")]
		public bool HideMenu
		{
			get { return Umbraco.Web.PublishedContentModels.Menu.GetHideMenu(this); }
		}

		///<summary>
		/// Menu Title (Indonesia)
		///</summary>
		[ImplementPropertyType("in_menuTitle")]
		public string In_menuTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Menu.GetIn_menuTitle(this); }
		}

		///<summary>
		/// Menu Title
		///</summary>
		[ImplementPropertyType("menuTitle")]
		public string MenuTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Menu.GetMenuTitle(this); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
